spring:
  datasource:
    username: root
    url: jdbc:h2:mem:testdb
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update